/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    BasePanel: typeof import('./src/components/BasePanel.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    ChinaMap: typeof import('./src/components/ChinaMap.vue')['default']
    FloatMenu: typeof import('./src/components/FloatMenu.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    ListLayout: typeof import('./src/components/Layout/ListLayout.vue')['default']
    ListMenu: typeof import('./src/components/ListMenu.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    MultiLevelTable: typeof import('./src/components/MultiLevelTable.vue')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    PlainButton: typeof import('./src/components/PlainButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
